// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/contact" | "/gallery" | "/new-yachts" | "/pages/coming-soon" | "/pages/gallery" | "/pages/login-2" | "/pages/login-3" | "/pages/other/404" | "/pages/other/about-1" | "/pages/other/about-2" | "/pages/other/about-3" | "/pages/other/condition" | "/pages/other/contact-1" | "/pages/other/contact-2" | "/pages/other/contact-3" | "/pages/other/faq" | "/pages/other/login-1" | "/pages/other/login-4" | "/pages/other/pricing" | "/pages/other/privacy" | "/pages/other/services" | "/pages/other/signup-1" | "/pages/other/team" | "/pages/other/testimonial" | "/pages/other/user-dashboard" | "/pages/portfolio/detail/portfolio-detail-1" | "/pages/portfolio/detail/portfolio-detail-2" | "/pages/portfolio/portfolio-2-grid" | "/pages/portfolio/portfolio-3-grid" | "/pages/portfolio/portfolio-4-grid" | "/pages/portfolio/portfolio-box-slider" | "/pages/portfolio/portfolio-creative-full" | "/pages/portfolio/portfolio-gallery-icon" | "/pages/portfolio/portfolio-image-change" | "/pages/portfolio/portfolio-modern" | "/pages/portfolio/portfolio-parallax" | "/pages/portfolio/portfolio-transform" | "/pages/portfolio/portfolio-vertical-slider" | "/pages/portfolio/portfolio-video-modal" | "/pages/signup-2" | "/pages/signup-3" | "/partners/[partnerId]" | "/services/brokerage" | "/services/brokerage/[id]" | "/services/charters" | "/services/transportation" | "/sign-in" | "/sign-up"
type AppRouteHandlerRoutes = "/api/admin/inquiries/[kind]/[id]/retry" | "/api/admin/partners" | "/api/admin/partners/[id]" | "/api/admin/tracking" | "/api/boats/[id]/inquiries" | "/api/categories" | "/api/contact" | "/api/notify" | "/api/partners/[slug]/inquiries" | "/api/products" | "/api/refresh-sitemap" | "/auth/callback"
type PageRoutes = "/_document"
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/_document": {}
  "/about": {}
  "/account": {}
  "/api/admin/inquiries/[kind]/[id]/retry": { "kind": string; "id": string; }
  "/api/admin/partners": {}
  "/api/admin/partners/[id]": { "id": string; }
  "/api/admin/tracking": {}
  "/api/boats/[id]/inquiries": { "id": string; }
  "/api/categories": {}
  "/api/contact": {}
  "/api/notify": {}
  "/api/partners/[slug]/inquiries": { "slug": string; }
  "/api/products": {}
  "/api/refresh-sitemap": {}
  "/auth/callback": {}
  "/contact": {}
  "/gallery": {}
  "/new-yachts": {}
  "/pages/coming-soon": {}
  "/pages/gallery": {}
  "/pages/login-2": {}
  "/pages/login-3": {}
  "/pages/other/404": {}
  "/pages/other/about-1": {}
  "/pages/other/about-2": {}
  "/pages/other/about-3": {}
  "/pages/other/condition": {}
  "/pages/other/contact-1": {}
  "/pages/other/contact-2": {}
  "/pages/other/contact-3": {}
  "/pages/other/faq": {}
  "/pages/other/login-1": {}
  "/pages/other/login-4": {}
  "/pages/other/pricing": {}
  "/pages/other/privacy": {}
  "/pages/other/services": {}
  "/pages/other/signup-1": {}
  "/pages/other/team": {}
  "/pages/other/testimonial": {}
  "/pages/other/user-dashboard": {}
  "/pages/portfolio/detail/portfolio-detail-1": {}
  "/pages/portfolio/detail/portfolio-detail-2": {}
  "/pages/portfolio/portfolio-2-grid": {}
  "/pages/portfolio/portfolio-3-grid": {}
  "/pages/portfolio/portfolio-4-grid": {}
  "/pages/portfolio/portfolio-box-slider": {}
  "/pages/portfolio/portfolio-creative-full": {}
  "/pages/portfolio/portfolio-gallery-icon": {}
  "/pages/portfolio/portfolio-image-change": {}
  "/pages/portfolio/portfolio-modern": {}
  "/pages/portfolio/portfolio-parallax": {}
  "/pages/portfolio/portfolio-transform": {}
  "/pages/portfolio/portfolio-vertical-slider": {}
  "/pages/portfolio/portfolio-video-modal": {}
  "/pages/signup-2": {}
  "/pages/signup-3": {}
  "/partners/[partnerId]": { "partnerId": string; }
  "/services/brokerage": {}
  "/services/brokerage/[id]": { "id": string; }
  "/services/charters": {}
  "/services/transportation": {}
  "/sign-in": {}
  "/sign-up": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
