// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type PagesPageConfig = {
  default: React.ComponentType<any> | ((props: any) => React.ReactNode | Promise<React.ReactNode> | never | void)
  getStaticProps?: (context: any) => Promise<any> | any
  getStaticPaths?: (context: any) => Promise<any> | any
  getServerSideProps?: (context: any) => Promise<any> | any
  getInitialProps?: (context: any) => Promise<any> | any
  /**
   * Segment configuration for legacy Pages Router pages.
   * Validated at build-time by parsePagesSegmentConfig.
   */
  config?: {
    amp?: boolean | 'hybrid' | string // necessary for JS
    maxDuration?: number
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    regions?: string[]
  }
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(mainBody)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/new-yachts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new-yachts">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/new-yachts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/404/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/404">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/404/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/about-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/about-1">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/about-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/about-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/about-2">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/about-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/about-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/about-3">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/about-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/condition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/condition">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/condition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/contact-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/contact-1">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/contact-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/contact-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/contact-2">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/contact-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/contact-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/contact-3">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/contact-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/faq">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/login-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/login-1">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/login-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/login-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/login-4">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/login-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/services">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/signup-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/signup-1">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/signup-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/team">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/testimonial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/testimonial">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/testimonial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/other/user-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/other/user-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/other/user-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/detail/portfolio-detail-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/detail/portfolio-detail-1">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/detail/portfolio-detail-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/detail/portfolio-detail-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/detail/portfolio-detail-2">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/detail/portfolio-detail-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-2-grid/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-2-grid">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-2-grid/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-3-grid/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-3-grid">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-3-grid/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-4-grid/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-4-grid">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-4-grid/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-box-slider/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-box-slider">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-box-slider/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-creative-full/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-creative-full">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-creative-full/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-gallery-icon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-gallery-icon">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-gallery-icon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-image-change/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-image-change">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-image-change/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-modern/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-modern">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-modern/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-parallax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-parallax">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-parallax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-transform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-transform">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-transform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-vertical-slider/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-vertical-slider">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-vertical-slider/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/pages/portfolio/portfolio-video-modal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/portfolio/portfolio-video-modal">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/pages/portfolio/portfolio-video-modal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/partners/[partnerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/[partnerId]">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/partners/[partnerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/services/brokerage/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/brokerage/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/services/brokerage/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/services/brokerage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/brokerage">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/services/brokerage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/services/charters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/charters">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/services/charters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(mainBody)/services/transportation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/transportation">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/services/transportation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other)/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/(other)/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other)/pages/coming-soon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/coming-soon">> = Specific
  const handler = {} as typeof import("../../src/app/(other)/pages/coming-soon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other)/pages/login-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/login-2">> = Specific
  const handler = {} as typeof import("../../src/app/(other)/pages/login-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other)/pages/login-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/login-3">> = Specific
  const handler = {} as typeof import("../../src/app/(other)/pages/login-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other)/pages/signup-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/signup-2">> = Specific
  const handler = {} as typeof import("../../src/app/(other)/pages/signup-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other)/pages/signup-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/signup-3">> = Specific
  const handler = {} as typeof import("../../src/app/(other)/pages/signup-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other)/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../src/app/(other)/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other)/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../src/app/(other)/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/inquiries/[kind]/[id]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inquiries/[kind]/[id]/retry">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/inquiries/[kind]/[id]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/partners/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/partners/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/partners/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/partners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/partners">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/partners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tracking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tracking">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tracking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/boats/[id]/inquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/boats/[id]/inquiries">> = Specific
  const handler = {} as typeof import("../../src/app/api/boats/[id]/inquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/categories/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partners/[slug]/inquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners/[slug]/inquiries">> = Specific
  const handler = {} as typeof import("../../src/app/api/partners/[slug]/inquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/refresh-sitemap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/refresh-sitemap">> = Specific
  const handler = {} as typeof import("../../src/app/api/refresh-sitemap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/pages/_document.tsx
{
  type __IsExpected<Specific extends PagesPageConfig> = Specific
  const handler = {} as typeof import("../../src/pages/_document.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}



// Validate ../../src/app/(mainBody)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(mainBody)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(other)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
